/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LayoutRouteRouteImport } from "./routes/_layout/route"
import { Route as LayoutnotFoundSplatRouteRouteImport } from "./routes/_layout/(not-found)/$/route"
import { Route as LayoutrootIndexRouteImport } from "./routes/_layout/(root)/index"
import { Route as LayoutIndustriesIndexRouteImport } from "./routes/_layout/industries/index"
import { Route as LayoutMoversIndexRouteImport } from "./routes/_layout/movers/index"
import { Route as LayoutStocksIndexRouteImport } from "./routes/_layout/stocks/index"
import { Route as LayoutStocksStockIdRouteRouteImport } from "./routes/_layout/stocks/$stockId/route"
import { Route as LayoutStocksStockIdIndexRouteImport } from "./routes/_layout/stocks/$stockId/index"

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: "/_layout",
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutnotFoundSplatRouteRoute =
  LayoutnotFoundSplatRouteRouteImport.update({
    id: "/(not-found)/$",
    path: "/$",
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutrootIndexRoute = LayoutrootIndexRouteImport.update({
  id: "/(root)/",
  path: "/",
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutIndustriesIndexRoute = LayoutIndustriesIndexRouteImport.update({
  id: "/industries/",
  path: "/industries/",
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutMoversIndexRoute = LayoutMoversIndexRouteImport.update({
  id: "/movers/",
  path: "/movers/",
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutStocksIndexRoute = LayoutStocksIndexRouteImport.update({
  id: "/stocks/",
  path: "/stocks/",
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutStocksStockIdRouteRoute =
  LayoutStocksStockIdRouteRouteImport.update({
    id: "/stocks/$stockId",
    path: "/stocks/$stockId",
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutStocksStockIdIndexRoute =
  LayoutStocksStockIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => LayoutStocksStockIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof LayoutrootIndexRoute
  "/$": typeof LayoutnotFoundSplatRouteRoute
  "/stocks/$stockId": typeof LayoutStocksStockIdRouteRouteWithChildren
  "/industries/": typeof LayoutIndustriesIndexRoute
  "/movers/": typeof LayoutMoversIndexRoute
  "/stocks/": typeof LayoutStocksIndexRoute
  "/stocks/$stockId/": typeof LayoutStocksStockIdIndexRoute
}
export interface FileRoutesByTo {
  "/$": typeof LayoutnotFoundSplatRouteRoute
  "/": typeof LayoutrootIndexRoute
  "/industries": typeof LayoutIndustriesIndexRoute
  "/movers": typeof LayoutMoversIndexRoute
  "/stocks": typeof LayoutStocksIndexRoute
  "/stocks/$stockId": typeof LayoutStocksStockIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_layout": typeof LayoutRouteRouteWithChildren
  "/_layout/(not-found)/$": typeof LayoutnotFoundSplatRouteRoute
  "/_layout/stocks/$stockId": typeof LayoutStocksStockIdRouteRouteWithChildren
  "/_layout/(root)/": typeof LayoutrootIndexRoute
  "/_layout/industries/": typeof LayoutIndustriesIndexRoute
  "/_layout/movers/": typeof LayoutMoversIndexRoute
  "/_layout/stocks/": typeof LayoutStocksIndexRoute
  "/_layout/stocks/$stockId/": typeof LayoutStocksStockIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$"
    | "/stocks/$stockId"
    | "/industries/"
    | "/movers/"
    | "/stocks/"
    | "/stocks/$stockId/"
  fileRoutesByTo: FileRoutesByTo
  to: "/$" | "/" | "/industries" | "/movers" | "/stocks" | "/stocks/$stockId"
  id:
    | "__root__"
    | "/_layout"
    | "/_layout/(not-found)/$"
    | "/_layout/stocks/$stockId"
    | "/_layout/(root)/"
    | "/_layout/industries/"
    | "/_layout/movers/"
    | "/_layout/stocks/"
    | "/_layout/stocks/$stockId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_layout/(not-found)/$": {
      id: "/_layout/(not-found)/$"
      path: "/$"
      fullPath: "/$"
      preLoaderRoute: typeof LayoutnotFoundSplatRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    "/_layout/(root)/": {
      id: "/_layout/(root)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutrootIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    "/_layout/industries/": {
      id: "/_layout/industries/"
      path: "/industries"
      fullPath: "/industries/"
      preLoaderRoute: typeof LayoutIndustriesIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    "/_layout/movers/": {
      id: "/_layout/movers/"
      path: "/movers"
      fullPath: "/movers/"
      preLoaderRoute: typeof LayoutMoversIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    "/_layout/stocks/": {
      id: "/_layout/stocks/"
      path: "/stocks"
      fullPath: "/stocks/"
      preLoaderRoute: typeof LayoutStocksIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    "/_layout/stocks/$stockId": {
      id: "/_layout/stocks/$stockId"
      path: "/stocks/$stockId"
      fullPath: "/stocks/$stockId"
      preLoaderRoute: typeof LayoutStocksStockIdRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    "/_layout/stocks/$stockId/": {
      id: "/_layout/stocks/$stockId/"
      path: "/"
      fullPath: "/stocks/$stockId/"
      preLoaderRoute: typeof LayoutStocksStockIdIndexRouteImport
      parentRoute: typeof LayoutStocksStockIdRouteRoute
    }
  }
}

interface LayoutStocksStockIdRouteRouteChildren {
  LayoutStocksStockIdIndexRoute: typeof LayoutStocksStockIdIndexRoute
}

const LayoutStocksStockIdRouteRouteChildren: LayoutStocksStockIdRouteRouteChildren =
  {
    LayoutStocksStockIdIndexRoute: LayoutStocksStockIdIndexRoute,
  }

const LayoutStocksStockIdRouteRouteWithChildren =
  LayoutStocksStockIdRouteRoute._addFileChildren(
    LayoutStocksStockIdRouteRouteChildren,
  )

interface LayoutRouteRouteChildren {
  LayoutnotFoundSplatRouteRoute: typeof LayoutnotFoundSplatRouteRoute
  LayoutStocksStockIdRouteRoute: typeof LayoutStocksStockIdRouteRouteWithChildren
  LayoutrootIndexRoute: typeof LayoutrootIndexRoute
  LayoutIndustriesIndexRoute: typeof LayoutIndustriesIndexRoute
  LayoutMoversIndexRoute: typeof LayoutMoversIndexRoute
  LayoutStocksIndexRoute: typeof LayoutStocksIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutnotFoundSplatRouteRoute: LayoutnotFoundSplatRouteRoute,
  LayoutStocksStockIdRouteRoute: LayoutStocksStockIdRouteRouteWithChildren,
  LayoutrootIndexRoute: LayoutrootIndexRoute,
  LayoutIndustriesIndexRoute: LayoutIndustriesIndexRoute,
  LayoutMoversIndexRoute: LayoutMoversIndexRoute,
  LayoutStocksIndexRoute: LayoutStocksIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
