/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as rootIndexRouteImport } from "./routes/(root)/index"
import { Route as DemoIndexRouteImport } from "./routes/demo/index"

const rootIndexRoute = rootIndexRouteImport.update({
  id: "/(root)/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: "/demo/",
  path: "/demo/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof rootIndexRoute
  "/demo/": typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof rootIndexRoute
  "/demo": typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/(root)/": typeof rootIndexRoute
  "/demo/": typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/demo/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/demo"
  id: "__root__" | "/(root)/" | "/demo/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  rootIndexRoute: typeof rootIndexRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(root)/": {
      id: "/(root)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof rootIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo/": {
      id: "/demo/"
      path: "/demo"
      fullPath: "/demo/"
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  rootIndexRoute: rootIndexRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
